# Generated by Django 2.2.7 on 2019-11-23 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Email do Cliente')),
                ('motherBoard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_board', to='products.MotherBoard', verbose_name='Placa Mãe')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor', to='products.Processor', verbose_name='Processador')),
                ('ramMemory', models.ManyToManyField(blank=True, related_name='ram_memory', to='products.RamMemory', verbose_name='Memória Ram')),
                ('videoBoard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_board', to='products.VideoBoard', verbose_name='Placa de Video')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
