# Generated by Django 2.2.7 on 2019-11-21 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191121_1107'),
        ('orders', '0003_remove_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ramMemory',
        ),
        migrations.AddField(
            model_name='order',
            name='ramMemory',
            field=models.ManyToManyField(related_name='ram_memory', to='products.RamMemory', verbose_name='Memória Ram'),
        ),
        migrations.AlterField(
            model_name='order',
            name='videoBoard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_board', to='products.VideoBoard', verbose_name='Placa de Video'),
        ),
    ]
