# Generated by Django 2.2.7 on 2019-11-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191121_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=1, max_length=100, verbose_name='Email do Cliente'),
            preserve_default=False,
        ),
    ]
