# Generated by Django 2.2.7 on 2019-11-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='RamMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=60, verbose_name='Produto')),
                ('size', models.IntegerField(verbose_name='Tamanho')),
            ],
            options={
                'verbose_name': 'Memória Ram',
                'verbose_name_plural': 'Memórias Ram',
            },
        ),
        migrations.CreateModel(
            name='VideoBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=60, unique=True, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Placa de Video',
                'verbose_name_plural': 'Placas de Video',
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=60, verbose_name='Produto')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marca', to='products.Brand')),
            ],
            options={
                'verbose_name': 'Processador',
                'verbose_name_plural': 'Processadores',
            },
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=60, unique=True, verbose_name='Produto')),
                ('ramSlots', models.IntegerField(verbose_name='Quantidade de Slots de Memória Ram')),
                ('maxMemorySize', models.IntegerField(verbose_name='Capacidade de Memória Ram Suportada')),
                ('videoOnboard', models.BooleanField(verbose_name='Video Integrado')),
                ('cpuSupport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_support', to='products.Brand')),
            ],
            options={
                'verbose_name': 'Placa Mãe',
                'verbose_name_plural': 'Placas Mãe',
            },
        ),
    ]
