# Generated by Django 2.2.7 on 2019-11-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboard',
            name='cpuSupport',
        ),
        migrations.AddField(
            model_name='motherboard',
            name='cpuSupport',
            field=models.ManyToManyField(related_name='cpu_support', to='products.Brand'),
        ),
    ]
