# Generated by Django 2.2.7 on 2019-11-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191121_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marca', to='products.Brand', verbose_name='Marca'),
        ),
    ]
